version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: php-web
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootwachtwoord
      MYSQL_DATABASE: mijn_database
      MYSQL_USER: gebruiker
      MYSQL_PASSWORD: gebruikerswachtwoord
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootwachtwoord

volumes:
  db_data:
